### ISSUE TITLE
Missing Module CMGL [Linux]

### ISSUE THREAD

**Issue by M3meZ** [fofix/fofix#100]
```
xenial)ku@localhost:~/Desktop/fofix-4.0.0alpha1/src$ python FoFiX.py 
Traceback (most recent call last):
  File "FoFiX.py", line 111, in <module>
    from GameEngine import GameEngine
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/GameEngine.py", line 46, in <module>
    from Data import Data
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Data.py", line 26, in <module>
    from Font import Font
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Font.py", line 26, in <module>
    import cmgl
ImportError: No module named cmgl
```

**Comment by M3meZ** [comment]
solved it when i did ./setup.py build && python setup.py install but theres a new issue

**Comment by M3meZ** [comment]
(xenial)ku@localhost:~/Desktop/fofix-4.0.0alpha1/src$ ./FoFiX.py 
Terminating due to unhandled exception:

Traceback (most recent call last):
  File "./FoFiX.py", line 298, in <module>
    main()
  File "./FoFiX.py", line 183, in main
    engine = GameEngine(config)
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/GameEngine.py", line 600, in __init__
    self.data = Data(self.resource, self.svg)
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Data.py", line 122, in __init__
    self.loadImgDrawing(self, "star1",   os.path.join("themes",themename,"star1.png"), textureSize = (128, 128))
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Data.py", line 443, in loadImgDrawing
    imgDrawing = self.getImgDrawing(fileName, dirLoad = dirLoad)
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Data.py", line 405, in getImgDrawing
    imgDrawing = ImgDrawing(self.svg, fileName1)
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Svg.py", line 74, in __init__
    self.texture = Texture(ImgData)
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Texture.py", line 64, in __init__
    self.loadFile(name)
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Texture.py", line 68, in loadFile
    self.loadImage(Image.open(name))
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Texture.py", line 75, in loadImage
    string = image.tostring('raw', 'RGBA', 0, -1)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 695, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.

If you make a bug report about this error, please include the contents of the following log file:
/home/ku/.fofix/fofix.log
The log file already includes the traceback given above.
Traceback (most recent call last):
  File "./FoFiX.py", line 298, in <module>
    main()
  File "./FoFiX.py", line 183, in main
    engine = GameEngine(config)
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/GameEngine.py", line 600, in __init__
    self.data = Data(self.resource, self.svg)
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Data.py", line 122, in __init__
    self.loadImgDrawing(self, "star1",   os.path.join("themes",themename,"star1.png"), textureSize = (128, 128))
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Data.py", line 443, in loadImgDrawing
    imgDrawing = self.getImgDrawing(fileName, dirLoad = dirLoad)
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Data.py", line 405, in getImgDrawing
    imgDrawing = ImgDrawing(self.svg, fileName1)
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Svg.py", line 74, in __init__
    self.texture = Texture(ImgData)
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Texture.py", line 64, in __init__
    self.loadFile(name)
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Texture.py", line 68, in loadFile
    self.loadImage(Image.open(name))
  File "/home/ku/Desktop/fofix-4.0.0alpha1/src/Texture.py", line 75, in loadImage
    string = image.tostring('raw', 'RGBA', 0, -1)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 695, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.

**Comment by wrzwicky** [comment]
According to StackExchange, you need an older version of Pillow:
https://askubuntu.com/questions/768416/tostring-has-been-removed-please-call-tobytes-instead

Strangely, I have 4.2.1 installed and have never seen this error, though maybe I'm just lucky.

**Comment by Linkid** [comment]
Hi!
I reformatted your issue with markdown.

Which version of Pillow are you using ?
Furthermore, I see you're using the alpha2 version of FoFiX. Maybe you should use the current sources of FoFiX. It should be fixed. We'll release soon the 4.0 version to avoid those recurrent issue ;).

**Comment by mdsitton** [comment]
If you notice in his bash path here, he is trying to run FoFiX Alpha 1 for some reason? This issue has been solved in master a long time ago, and i see this issue as being wonfix..

Once we release a new version this will become a non-issue, closing.
