### ISSUE TITLE
Missing keys in fofix.ini prevent start

### ISSUE THREAD

**Issue by DeX77** [fofix/fofix#15]
fofix will show a window but crash when trying to enable shaders:

/FoFiX.py 
SDL_JoystickNumHats value:1:
Terminating due to unhandled exception:

Traceback (most recent call last):
  File "./FoFiX.py", line 278, in <module>
    main()
  File "./FoFiX.py", line 233, in main
    while engine.run():
  File "/home/dex/fofix/src/GameEngine.py", line 823, in run
    return self.mainloop()
  File "/home/dex/fofix/src/GameEngine.py", line 681, in loading
    self.view.pushLayer(self.startupLayer)
  File "/home/dex/fofix/src/View.py", line 143, in pushLayer
    layer.shown()
  File "/home/dex/fofix/src/MainMenu.py", line 229, in shown
    shaders.checkIfEnabled()
  File "/home/dex/fofix/src/Shader.py", line 492, in checkIfEnabled
    if Config.get("theme","shader_"+i) == "True":
  File "/home/dex/fofix/src/Config.py", line 277, in get
    return config.get(section, option)
  File "/home/dex/fofix/src/Config.py", line 170, in get
    type    = self.prototype[section][option].type
KeyError: 'shader_neck'

fofix.log shows:
[    1.426245] (E) Config key theme.shader_neck not defined while reading ~/.fofix/fofix.ini.

Guess this belongs to commit 237ccb45e3eda98b00459110d47a939c7d837f41

My fofix.ini is generated by the program at start.

**Comment by mdsitton** [comment]
This was fixed some time ago.
