### ISSUE TITLE
Extension name 'fofix.lib.cmgl' does not match fully qualified name 

### ISSUE THREAD

**Issue by JohnyGemityg** [fofix/fofix#153]
Hi

Im looking forward to play this oldschool game.

When i run 
`[john@john-gem fofix] $ python setup.py build_ext --inplace --force`

I got this error:
```
checking for program pkg-config... /usr/bin/pkg-config
checking for library ogg... ok
checking for library theoradec... ok
checking for library glib-2.0... ok
checking for library libswscale... ok
checking for library gl... ok
Warning: Extension name 'fofix.lib.cmgl' does not match fully qualified name 'fofix.core.cmgl.cmgl' of 'fofix/core/cmgl/cmgl.pyx'
Traceback (most recent call last):
  File "setup.py", line 482, in <module>
    'ext_modules': cythonize(extensions),
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 920, in cythonize
    aliases=aliases)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
    kwds = deps.distutils_info(file, aliases, base).values
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 670, in distutils_info
    return (self.transitive_merge(filename, self.distutils_info0, DistutilsInfo.merge)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 680, in transitive_merge
    node, extract, merge, seen, {}, self.cimported_files)[0]
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 685, in transitive_merge_helper
    deps = extract(node)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 654, in distutils_info0
    externs = _make_relative(externs, basedir)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 86, in _make_relative
    for path in file_paths]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 14: ordinal not in range(128)
```

Does anyone know how to fix this.

`Linux john-gem 4.14.18-300.fc27.x86_64 #1 SMP Thu Feb 8 01:35:31 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Fedora 27

Thanks

**Comment by Linkid** [comment]
Hi!
I can't reproduce your bug. Which version of `cython` are you using ?

**Comment by Linkid** [comment]
Hi!

To reproduce your bug, I set up a VM with Fedora 27, installed python2 and all the FoFiX dependencies, and git cloned this repo. I tried to run the ``build_ext`` command, and the compilation phase worked well. So, I didn't managed to reproduce your error :/.

Could you give more information about your environment, please:
- are you using a virtualenv?
- which version of python are you using?
- do your working directory contains "special characters"?

Thanks

**Comment by Linkid** [comment]
I consider this bug as closed. First because I can't reproduce it entirely, and then because the cmgl extension is going to be replaced with a pure python one.
