### ISSUE TITLE
KeyError: 'log_class_inits' when starting drums practice

### ISSUE THREAD

**Issue by clementbellot** [fofix/fofix#160]
When I start the drums practice in the training section, I get an Error :
```
Traceback (most recent call last):
  File ".\FoFiX.py", line 275, in <module>
    main.run()
  File ".\FoFiX.py", line 256, in run
    while self.engine.run():
  File "D:\Game\Fofix\fofix\core\GameEngine.py", line 630, in run
    rtn = self.mainloop()
  File "D:\Game\Fofix\fofix\core\GameEngine.py", line 612, in main
    done = self.task.run()
  File "C:\Python27\lib\site-packages\fretwork\task.py", line 118, in run
    self.runTask(taskData['task'])
  File "C:\Python27\lib\site-packages\fretwork\task.py", line 93, in runTask
    task.run(tick)
  File "D:\Game\Fofix\fofix\core\Input.py", line 326, in run
    self.broadcastEvent(self.keyListeners, "keyPressed", event.key, event.unicode)
  File "D:\Game\Fofix\fofix\core\Input.py", line 237, in broadcastEvent
    if getattr(l, function)(*args):
  File "D:\Game\Fofix\fofix\game\SongChoosingScene.py", line 793, in keyPressed
    self.startGame()
  File "D:\Game\Fofix\fofix\game\SongChoosingScene.py", line 567, in startGame
    self.engine.world.createScene("GuitarScene", libraryName=self.libraryName, songName=self.songName)
  File "D:\Game\Fofix\fofix\game\World.py", line 124, in createScene
    self.scene = SceneFactory.create(engine = self.engine, name = name, **args)
  File "D:\Game\Fofix\fofix\core\SceneFactory.py", line 36, in create
    return getattr(scene_name, name)(engine = engine, **args)
  File "D:\Game\Fofix\fofix\game\guitarscene\GuitarScene.py", line 705, in __init__
    inst = Drum(self.engine, player, self, player=j)
  File "D:\Game\Fofix\fofix\game\guitarscene\instruments\Drum.py", line 111, in __init__
    self.logClassInits = self.engine.config.get("game", "log_class_inits")
  File "D:\Game\Fofix\fofix\core\Config.py", line 197, in get
    type    = self.prototype[section][option].type
KeyError: 'log_class_inits'
```

Changing `fofix\game\guitarscene\instruments\Drum.py` line 111 to be `self.logClassInits = self.engine.config.get("game", "log_class_inits")` instead of `self.logClassInits = self.engine.config.get("log", "log_class_inits")` seemed to have fixed it.

(That issue is as of 2e27c0d, the latest version at this time)

**Comment by Linkid** [comment]
Hi!

Thanks for this issue :). I tagged it for the next release.

**Comment by Linkid** [comment]
Done. Thanks again :).
