### ISSUE TITLE
Start error: 'NoneType' object has no attribute 'set'

### ISSUE THREAD

**Issue by Linkid** [fofix/fofix#205]
When starting the game, there is an error which stop the program. Here is the traceback:
```
Traceback (most recent call last):
  File "FoFiX.py", line 155, in <module>
    from fofix.core.VideoPlayer import VideoLayer, VideoPlayerError
  File "/xxx/fofix/fofix/core/VideoPlayer/__init__.py", line 1, in <module>
    from fofix.lib._VideoPlayer import *
  File "/xxx/fofix/fofix/core/VideoPlayer/_VideoPlayer.pyx", line 100, in init fofix.core.VideoPlayer._VideoPlayer
    from fofix.core.Input import KeyListener
  File "/xxx/fofix/fofix/core/Input.py", line 41, in <module>
    from fofix.core.Player import Controls
  File "/xxx/fofix/fofix/core/Player.py", line 31, in <module>
    from fofix.core.Language import _
  File "/xxx/fofix/fofix/core/Language.py", line 55, in <module>
    Config.set("game", "language", "")
  File "/xxx/fofix/fofix/core/Config.py", line 313, in set
    return config.set(section, option, value)
AttributeError: 'NoneType' object has no attribute 'set'
```

**Comment by Linkid** [comment]
Using fretwork 0.3, I'm able to have more logs in `fofix.log`:
`fofix.core.Language - WARNING - Unable to select language 'French': [Errno 2] No such file or directory: u'/tmp/fofix/data/translations/french.mo'`.

When I remove the language in my `fofix.ini` file, the game is working.

**Comment by Linkid** [comment]
A solution is to generate translations before launching the game, if a language has been chosen: `python setup.py msgfmt`
