### ISSUE TITLE
Missing DLL when starting FoFiX.py

### ISSUE THREAD

**Issue by Rexrder** [fofix/fofix#208]
I've been trying to start ```FoFiX.py``` but it seems like there is a missing DLL over there.
There you have the error:
```PS D:\Users\admin\Documents\fofix> python FoFiX.py
Traceback (most recent call last):
  File "FoFiX.py", line 129, in <module>
    from fofix.game.Main import Main
  File "D:\Users\admin\Documents\fofix\fofix\game\Main.py", line 41, in <module>
    from fofix.core.VideoPlayer import VideoLayer, VideoPlayerError
  File "D:\Users\admin\Documents\fofix\fofix\core\VideoPlayer\__init__.py", line 1, in <module>
    from fofix.lib._VideoPlayer import *
ImportError: DLL load failed: No se puede encontrar el m¾dulo especificado.
```
I'm using Windows 10 64-bits and Python 2.7
Thanks

**Comment by AEFeinstein** [comment]
I think I'm seeing the same thing, or something similar. in `\fofix\fofix\core\VideoPlayer\__init__.py`
```
Exception has occurred: ImportError
DLL load failed: %1 is not a valid Win32 application.
  File "D:\Program Files\fofix\fofix\core\VideoPlayer\__init__.py", line 1, in <module>
    from fofix.lib._VideoPlayer import *
  File "D:\Program Files\fofix\fofix\game\Main.py", line 41, in <module>
    from fofix.core.VideoPlayer import VideoLayer, VideoPlayerError
  File "D:\Program Files\fofix\FoFiX.py", line 129, in <module>
    from fofix.game.Main import Main
```
I'm using Python 2.7.16, 32 bit, on Windows 10 (64 bit)

**Comment by AEFeinstein** [comment]
The revision that broke this was 17267204a5407670035f59c20c23724c8e251923. If I check out the prior revision, c92bb2473030890b3a4a5a54ec0e4637b85b7b9c, it runs fine.

**Comment by Rexrder** [comment]
I tried to start it in that revision, but it seems that it's still not working. Just that now, the app ends with exit code 1, so I don't know what happened. If you have any idea, I would really appreciate your help.

**Comment by AEFeinstein** [comment]
What's the new traceback say?

**Comment by AEFeinstein** [comment]
@Linkid this is still an issue as of 5379ce0b586e79d21877272ac088ecfa04e6f891:

```
PS C:\Users\AFeinstein\Desktop\fofix> C:\Python27\python.exe .\FoFiX.py
Traceback (most recent call last):
  File ".\FoFiX.py", line 129, in <module>
    from fofix.game.Main import Main
  File "C:\Users\AFeinstein\Desktop\fofix\fofix\game\Main.py", line 41, in <module>
    from fofix.core.VideoPlayer import VideoLayer, VideoPlayerError
  File "C:\Users\AFeinstein\Desktop\fofix\fofix\core\VideoPlayer\__init__.py", line 1, in <module>
    from fofix.lib._VideoPlayer import *
ImportError: DLL load failed: The specified module could not be found.
```

I also noticed that the compilation has a warning about `VideoPlayer` too. I don't know if that's related or not.

```
PS C:\Users\AFeinstein\Desktop\fofix> C:\Python27\python.exe setup.py build_ext --inplace --force
checking for program pkg-config... .\win32\deps\bin\pkg-config.exe
checking for library ogg... ok
checking for library theoradec... ok
checking for library glib-2.0... ok
checking for library libswscale... ok
Warning: Extension name 'fofix.lib._VideoPlayer' does not match fully qualified name 'fofix.core.VideoPlayer._VideoPlayer' of 'fofix/core/VideoPlayer/_VideoPlayer.pyx'
running build_ext
building 'fofix.lib._VideoPlayer' extension
C:\Users\AFeinstein\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Dinline=__inline -Ifofix/core/VideoPlayer -IC:/Users/AFeinstein/Desktop/fofix/win32/deps/include -IC:/Users/AFeinstein/Desktop/fofix/win32/deps/include/glib-2.0 -IC:/Users/AFeinstein/Desktop/fofix/win32/deps/lib/glib-2.0/include -I. -Iwin32/deps/include/msinttypes -IC:\Python27\include -IC:\Python27\PC /Tcfofix/core/VideoPlayer/_VideoPlayer.c /Fobuild\temp.win32-2.7\Release\fofix/core/VideoPlayer/_VideoPlayer.obj
_VideoPlayer.c
C:\Users\AFeinstein\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Dinline=__inline -Ifofix/core/VideoPlayer -IC:/Users/AFeinstein/Desktop/fofix/win32/deps/include -IC:/Users/AFeinstein/Desktop/fofix/win32/deps/include/glib-2.0 -IC:/Users/AFeinstein/Desktop/fofix/win32/deps/lib/glib-2.0/include -I. -Iwin32/deps/include/msinttypes -IC:\Python27\include -IC:\Python27\PC /Tcfofix/core/VideoPlayer/VideoPlayer.c /Fobuild\temp.win32-2.7\Release\fofix/core/VideoPlayer/VideoPlayer.obj
VideoPlayer.c
C:\Users\AFeinstein\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:/Users/AFeinstein/Desktop/fofix/win32/deps/lib /LIBPATH:C:/Users/AFeinstein/Desktop/fofix/win32/deps/lib /LIBPATH:C:/Users/AFeinstein/Desktop/fofix/win32/deps/lib /LIBPATH:C:/Users/AFeinstein/Desktop/fofix/win32/deps/lib /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild /LIBPATH:C:\Python27\PC\VS9.0 opengl32.lib ogg.lib theoradec.lib ogg.lib glib-2.0.lib intl.lib swscale.lib /EXPORT:init_VideoPlayer build\temp.win32-2.7\Release\fofix/core/VideoPlayer/_VideoPlayer.obj build\temp.win32-2.7\Release\fofix/core/VideoPlayer/VideoPlayer.obj /OUT:build\lib.win32-2.7\fofix\lib\_VideoPlayer.pyd /IMPLIB:build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.lib /MANIFESTFILE:build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.pyd.manifest
   Creating library build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.lib and object build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.exp
copying build\lib.win32-2.7\fofix\lib\_VideoPlayer.pyd -> fofix\lib
```

**Comment by Linkid** [comment]
Hi !
About the DLL loading failure: can you put the log of the `build_ext` command, please ? Do you have the right dependencies DLL in your PATH ? I only reproduced it by removing dependencies DLL only.

About the Cython warning: this is just a warning to tell us that the `_VideoPlayer` compiled lib is not at the expected location.
Futhermore, I'm trying to remove extension modules like this one to build them in a seperate and easy way. Then, this warning will be removed ;). See https://github.com/fofix/fofix/issues/128#issuecomment-602757716.

**Comment by AEFeinstein** [comment]
`build_ext` didn't create any logs that I could find, but I did a fresh clone of the repo, ran it again, and this was all the output:
```
PS C:\Users\AFeinstein\Desktop\fofix> C:\Python27\python.exe setup.py build_ext --inplace --force
checking for program pkg-config... .\win32\deps\bin\pkg-config.exe
checking for library ogg... ok
checking for library theoradec... ok
checking for library glib-2.0... ok
checking for library libswscale... ok
Warning: Extension name 'fofix.lib._VideoPlayer' does not match fully qualified name 'fofix.core.VideoPlayer._VideoPlayer' of 'fofix/core/VideoPlayer/_VideoPlayer.pyx'
Compiling fofix/core/VideoPlayer/_VideoPlayer.pyx because it changed.
[1/1] Cythonizing fofix/core/VideoPlayer/_VideoPlayer.pyx
running build_ext
building 'fofix.lib._VideoPlayer' extension
creating build
creating build\temp.win32-2.7
creating build\temp.win32-2.7\Release
creating build\temp.win32-2.7\Release\fofix
creating build\temp.win32-2.7\Release\fofix\core
creating build\temp.win32-2.7\Release\fofix\core\VideoPlayer
C:\Users\AFeinstein\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Dinline=__inline -Ifofix/core/VideoPlayer -IC:/Users/AFeinstein/Desktop/fofix/win32/deps/include -IC:/Users/AFeinstein/Desktop/fofix/win32/deps/include/glib-2.0 -IC:/Users/AFeinstein/Desktop/fofix/win32/deps/lib/glib-2.0/include -I. -Iwin32/deps/include/msinttypes -IC:\Python27\include -IC:\Python27\PC /Tcfofix/core/VideoPlayer/_VideoPlayer.c /Fobuild\temp.win32-2.7\Release\fofix/core/VideoPlayer/_VideoPlayer.obj
_VideoPlayer.c
C:\Users\AFeinstein\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Dinline=__inline -Ifofix/core/VideoPlayer -IC:/Users/AFeinstein/Desktop/fofix/win32/deps/include -IC:/Users/AFeinstein/Desktop/fofix/win32/deps/include/glib-2.0 -IC:/Users/AFeinstein/Desktop/fofix/win32/deps/lib/glib-2.0/include -I. -Iwin32/deps/include/msinttypes -IC:\Python27\include -IC:\Python27\PC /Tcfofix/core/VideoPlayer/VideoPlayer.c /Fobuild\temp.win32-2.7\Release\fofix/core/VideoPlayer/VideoPlayer.obj
VideoPlayer.c
creating build\lib.win32-2.7
creating build\lib.win32-2.7\fofix
creating build\lib.win32-2.7\fofix\lib
C:\Users\AFeinstein\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:/Users/AFeinstein/Desktop/fofix/win32/deps/lib /LIBPATH:C:/Users/AFeinstein/Desktop/fofix/win32/deps/lib /LIBPATH:C:/Users/AFeinstein/Desktop/fofix/win32/deps/lib /LIBPATH:C:/Users/AFeinstein/Desktop/fofix/win32/deps/lib /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild /LIBPATH:C:\Python27\PC\VS9.0 opengl32.lib ogg.lib theoradec.lib ogg.lib glib-2.0.lib intl.lib swscale.lib /EXPORT:init_VideoPlayer build\temp.win32-2.7\Release\fofix/core/VideoPlayer/_VideoPlayer.obj build\temp.win32-2.7\Release\fofix/core/VideoPlayer/VideoPlayer.obj /OUT:build\lib.win32-2.7\fofix\lib\_VideoPlayer.pyd /IMPLIB:build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.lib /MANIFESTFILE:build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.pyd.manifest
   Creating library build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.lib and object build\temp.win32-2.7\Release\fofix/core/VideoPlayer\_VideoPlayer.exp
copying build\lib.win32-2.7\fofix\lib\_VideoPlayer.pyd -> fofix\lib
```

Here are all the DLL files in `fofix` after building. I don't see anything like VideoPlayer.dll. What DLL am I looking for? Should I add `./win32/deps/bin/` to my system path variable?

```
PS C:\Users\AFeinstein\Desktop\fofix> find . -iname *.dll
./win32/deps/bin/avutil-52.dll
./win32/deps/bin/iconv.dll
./win32/deps/bin/libffi-6.dll
./win32/deps/bin/libFLAC-8.dll
./win32/deps/bin/libfreetype-6.dll
./win32/deps/bin/libgettextlib-0-18-2.dll
./win32/deps/bin/libgettextpo-0.dll
./win32/deps/bin/libgettextsrc-0-18-2.dll
./win32/deps/bin/libglib-2.0-0.dll
./win32/deps/bin/libgthread-2.0-0.dll
./win32/deps/bin/libintl-8.dll
./win32/deps/bin/libjpeg-9.dll
./win32/deps/bin/libogg-0.dll
./win32/deps/bin/libpng15-15.dll
./win32/deps/bin/libportaudio-2.dll
./win32/deps/bin/libsmf-0.dll
./win32/deps/bin/libSoundTouch-0.dll
./win32/deps/bin/libtheora-0.dll
./win32/deps/bin/libtheoradec-1.dll
./win32/deps/bin/libtheoraenc-1.dll
./win32/deps/bin/libvorbis-0.dll
./win32/deps/bin/libvorbisenc-2.dll
./win32/deps/bin/libvorbisfile-3.dll
./win32/deps/bin/portmidi.dll
./win32/deps/bin/porttime.dll
./win32/deps/bin/SDL.dll
./win32/deps/bin/SDL_image.dll
./win32/deps/bin/SDL_mixer.dll
./win32/deps/bin/SDL_ttf.dll
./win32/deps/bin/swscale-2.dll
./win32/deps/bin/zlib1.dll
```

#128 is very promising!

**Comment by JHoule** [comment]
I noticed that the PATH envvar is modified later in the code to allow loading DLLs.

Moving this code before the imports in FoFiX.py resolved the problem for me, e.g.:

```
diff --git a/FoFiX.py b/FoFiX.py
index a856fe9a..9ff6ae23 100644
--- a/FoFiX.py
+++ b/FoFiX.py
@@ -124,6 +124,11 @@ if __name__ == '__main__':
     log.configure(logfile)
     logger = logging.getLogger(__name__)

+    # Add the directory of DLL dependencies to the PATH if we're running
+    # from source on Windows so we pick them up when those bits are imported.
+    if is_windows and not hasattr(sys, 'frozen'):
+        os.environ['PATH'] = os.path.abspath(os.path.join('.', 'win32', 'deps', 'bin')) + os.pathsep + os.environ['PATH']
+
     # Imports
     import fretwork
     from fofix.game.Main import Main
@@ -137,11 +142,6 @@ if __name__ == '__main__':
             run_command('defaults write org.python.python ApplePersistenceIgnoreState 0')
             atexit.register(run_command, 'defaults write org.python.python ApplePersistenceIgnoreState %s' % data)

-    # Add the directory of DLL dependencies to the PATH if we're running
-    # from source on Windows so we pick them up when those bits are imported.
-    if is_windows and not hasattr(sys, 'frozen'):
-        os.environ['PATH'] = os.path.abspath(os.path.join('.', 'win32', 'deps', 'bin')) + os.pathsep + os.environ['PATH']
-
     fretworkRequired = (0, 4, 0)
     reqVerStr = '.'.join([str(i) for i in fretworkRequired])
     fretworkErrorStr = '''
```

**Comment by Linkid** [comment]
@JHoule Great :). Could you make a PR to fix this issue, please ?
Thank you

**Comment by Linkid** [comment]
@AEFeinstein @Rexrder: could you tell me if the @JHoule patch fixed this issue for you too, please ? If this is enough, we will be able to close this issue, then :).

**Comment by AEFeinstein** [comment]
I'll try this out in the coming days and let you know.

**Comment by AEFeinstein** [comment]
Well, I think it solved the missing DLL problem, though now I have this error instead. I'll see what can be done about it

![image](https://user-images.githubusercontent.com/231180/87113125-89dc5a00-c23b-11ea-865c-915f035830bd.png)

**Comment by JHoule** [comment]
Sounds related to PyOpenGL bindings (or maybe PyOpenGL-accelerate) this time around.  Are you using 32-bit Python 2 version?  I wasn't able to get it to work with Python 3 nor 64-bit.

At least, the DLL part is fixed. ;-)

**Comment by AEFeinstein** [comment]
I have Python 2, 32-bit installed just for FoFiX. I swear it used to work...
```
Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)] on win32
```

The strange thing to me is that `draw_arrays` does exist in `cmgl.py`, but it can't be found when running? It almost feels like more of a Python issue than a bindings one.
```
def draw_arrays(mode, vertices, colors=None, texcoords=None):
    """ Draw a triangle

    :param mode: mode to render (triangle, etc.)
    :param vertices: an array of vertex data
    :param colors: an array of colors (optional)
    :param texcoords: an array of texture coordinates (optional)
    """
```

**Comment by JHoule** [comment]
I'm at 2.7.18, using virtualenv.

Here is my output of `pip freeze`:
```
Cerealizer==0.8.2
Cython==0.27.3
docutils==0.16
fretwork==0.4.0
numpy==1.13.3
olefile==0.44
Pillow==6.2.2
PyAudio==0.2.11
pygame==1.9.3
PyOpenGL==3.1.0
PyOpenGL-accelerate==3.1.0
pypitch==1.2
pypiwin32==223
pywin32==228
```

**Comment by AEFeinstein** [comment]
Figured it out. In https://github.com/fofix/fofix/commit/8edf234b513454976b7c6e3a172568908a300f5d#diff-5e1a5f56c03dd4571fdbec7191e94812 `drawArrays` was renamed to `draw_arrays`. I had some stale object file which still had `drawArrays` even though the source had `draw_arrays`. Cleaning and building got me running again. And by cleaning I mean `find . -iname "*.py[c|d]" -delete`.

**Comment by Linkid** [comment]
Yes, cleaning the environment is necessary with this changeset.
@JHoule : about the python version, feel free to read this post : https://fofix.github.io/blog/moving-to-python3.html.

I can now close this issue. Thank you, both of you :).

**Comment by AEFeinstein** [comment]
Welcome!
