### ISSUE TITLE
Exit when loading songs list

### ISSUE THREAD

**Issue by wilsoft-gt** [fofix/fofix#209]
I get the following error when I try to play a song, it happens when the game loads the songs list

> Traceback (most recent call last):
  File "FoFiX.py", line 171, in <module>
    main.run()
  File "/home/wilson/juegos/fofix/fofix/game/Main.py", line 131, in run
    while self.engine.run():
  File "/home/wilson/juegos/fofix/fofix/core/GameEngine.py", line 630, in run
    rtn = self.mainloop()
  File "/home/wilson/juegos/fofix/fofix/core/GameEngine.py", line 612, in main
    done = self.task.run()
  File "/home/wilson/.local/lib/python2.7/site-packages/fretwork/task.py", line 118, in run
    self.runTask(taskData['task'])
  File "/home/wilson/.local/lib/python2.7/site-packages/fretwork/task.py", line 93, in runTask
    task.run(tick)
  File "/home/wilson/juegos/fofix/fofix/core/Input.py", line 326, in run
    self.broadcastEvent(self.keyListeners, "keyPressed", event.key, event.unicode)
  File "/home/wilson/juegos/fofix/fofix/core/Input.py", line 237, in broadcastEvent
    if getattr(l, function)(*args):
  File "/home/wilson/juegos/fofix/fofix/game/Lobby.py", line 345, in keyPressed
    self.engine.world.startGame()
  File "/home/wilson/juegos/fofix/fofix/game/World.py", line 86, in startGame
    self.createScene(STARTUP_SCENE, **args)
  File "/home/wilson/juegos/fofix/fofix/game/World.py", line 124, in createScene
    self.scene = SceneFactory.create(engine = self.engine, name = name, **args)
  File "/home/wilson/juegos/fofix/fofix/core/SceneFactory.py", line 36, in create
    return getattr(scene_name, name)(engine = engine, **args)
  File "/home/wilson/juegos/fofix/fofix/game/SongChoosingScene.py", line 69, in __init__
    song.updateSongDatabase(self.engine)
  File "/home/wilson/juegos/fofix/fofix/game/song/song.py", line 3523, in updateSongDatabase
    getAvailableSongs(engine, folder.libraryName, progressCallback=lambda p: updatePhase('%s \n %s \n %s' % (
  File "/home/wilson/juegos/fofix/fofix/game/song/song.py", line 3117, in getAvailableSongs
    library, name, "song.ini", writable=True), library))
  File "/home/wilson/juegos/fofix/fofix/game/song/song.py", line 274, in __init__
    self.getScores(part)
  File "/home/wilson/juegos/fofix/fofix/game/song/song.py", line 329, in getScores
    self.highScores[str(part)] = {}
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 10: ordinal not in range(128)

**Comment by Linkid** [comment]
Hi !
Did you try with another folder of songs ?

**Comment by wilsoft-gt** [comment]
> Hi !
> Did you try with another folder of songs ?

Yes, I even try to create a new folder in the game folder with just one song and I have the same issue. Btw My OS is ubuntu 18.04.1

**Comment by wilsoft-gt** [comment]
I fixed this, I search for the error and it seems that the only way to fix this is changing the hole script to UTF8 by adding the follosing lines at the top of the script:

```
# encoding=utf8
import sys
reload(sys)
sys.setdefaultencoding('utf8')
```
check #211 04dd680 to fix the issue

**Comment by Linkid** [comment]
As I said in your PR, I'm not fan of this solution…
Could you share logs (see `fofix.log`) and some test cases to reproduce your issue, please ?

**Comment by AEFeinstein** [comment]
https://github.com/fofix/fofix/pull/189 tried to solve this too

**Comment by AEFeinstein** [comment]
You should be able to replicate this by having a song folder named "06 Mötley Crüe - Shout At The Devil" with a song.ini that looks like
```
[song]
name = Shout At The Devil
artist = Mötley Crüe
album = Shout At The Devil
year = 1983
genre = Heavy Metal
tags = cover
icon = gh2
unlock_id = gh2_1enc
unlock_require = gh2_1
unlock_text = Finish All Songs In This Tier To Unlock The Encore
diff_guitar = 0
diff_bass = 0
```
