### ISSUE TITLE
Fofix can't start

### ISSUE THREAD

**Issue by Katana7** [fofix/fofix#213]
Hello i can't start fofix anymore i have this error log

[    0.000000] (D) Logging initialized: Sun Mar 29 21:47:04 2020
[    0.171000] (D) Checking MIDI output ports for a wavetable or synth for sound generation...
[    0.171000] (D) MIDI output port count = 1
[    0.171000] (D) MIDI Output port 0 found: Microsoft GS Wavetable Synth
[    0.207000] (D) GameEngine class init (GameEngine.py)...
[    0.207000] (D) FoFiX v3.121 Final starting up...
[    0.207000] (D) pygame version: 1.9.1release-svn2575
[    0.207000] (D) Initializing audio.
[    0.501000] (D) Audio configuration: (44100, -16, 2)
[    0.525000] (D) Initializing pygame.mixer & audio system at 44100 Hz.
[    0.525000] (D) Initializing video.
[    1.301000] (E) Terminating due to unhandled exception: 
Traceback (most recent call last):
  File "FoFiX.py", line 276, in <module>
  File "FoFiX.py", line 175, in main
  File "GameEngine.pyo", line 550, in __init__
  File "Video.pyo", line 130, in setMode
error: (6, 'CreateIconFromResource', 'Descripteur non valide')
**To Reproduce**
Steps to reproduce the behavior.

I'm on Win 7 x64
Python 2.6 and 2.7 installed

**Comment by AEFeinstein** [comment]
@Katana7 can you start it now that #224 has been merged?

**Comment by Katana7** [comment]
I don't now how to update
How i can?

**Comment by AEFeinstein** [comment]
If you downloaded the project as a zip before, do that again. If you checked it out with git, navigate to the directory and run `git pull`

**Comment by Linkid** [comment]
@Katana7 : hi! Do you have this error with the current code base ? Can we close this issue ?
Thank you again :)

**Comment by Katana7** [comment]
I have the same error with all release :(

**Comment by Linkid** [comment]
Logs are saying that your version is the v3.121. I've updated the title of the issue.

**Comment by Linkid** [comment]
#264 seems to have an equivalent issue with the icon.
