### ISSUE TITLE
[3.122] To String Error when running python FoFiX.py

### ISSUE THREAD

**Issue by Derpez** [fofix/fofix#255]
When I run FoFiX.py It Gives Me An Error

This Is The Error From the log file
```
[    0.000000] (D) Logging initialized: Mon Aug 30 11:16:29 2021
[    0.364000] (W) Pitch bending is not supported; install john.stumpo's pitchbend module (r7 or higher) if you want it.
[    0.365000] (W) PyOGG not found. OGG files will be fully decoded prior to playing; expect absurd memory usage.
[    0.541000] (D) GameEngine class init (GameEngine.py)...
[    0.541000] (D) FoFiX v3.122 Final starting up...
[    0.541000] (D) pygame version: 1.9.6
[    0.542000] (D) Initializing audio.
[    0.818000] (D) Audio configuration: (44100, -16, 2)
[    0.841000] (D) Initializing pygame.mixer & audio system at 44100 Hz.
[    0.841000] (D) Initializing video.
[    1.085000] (E) Terminating due to unhandled exception: 
Traceback (most recent call last):
  File "FoFiX.py", line 276, in <module>
    main()
  File "FoFiX.py", line 175, in main
    engine = GameEngine(config)
  File "C:\Users\***\Downloads\fofix-3.122\fofix-3.122\src\GameEngine.py", line 550, in __init__
    self.video.setMode((width, height), fullscreen = fullscreen, multisamples = multisamples)
  File "C:\Users\***\Downloads\fofix-3.122\fofix-3.122\src\Video.py", line 114, in setMode
    bigIconColorData = bigIcon.tostring()
AttributeError: 'Image' object has no attribute 'tostring'
```

Im On Windows 10 BTW

**Comment by Linkid** [comment]
Hi ! Thank your for this issue.

**Comment by Derpez** [comment]
How to fix?

**Comment by Linkid** [comment]
There are still some old PIL functions that need to be removed. Do you want to try a fix ?

**Comment by Derpez** [comment]
Ive already spent countless hours trying to fix it but after something another error appears

**Comment by Linkid** [comment]
If you want, you can come to our chat and let me look at your code ;). Or I can try to submit a patch.

**Comment by Linkid** [comment]
Should be fixed, now.
