### ISSUE TITLE
Runtime errors with Python 2.7.18

### ISSUE THREAD

**Issue by Nutzzz** [fofix/fofix#264]
**Describe the bug**
Using FoFiX 3.122 or 3.123 and Python 2.7.18 (x86) in Windows 11, once dependencies have been resolved and FoFiX is successfully building, I get a runtime error in FoFiX.exe.log: "ImportError: No module named difflib."  It looks like difflib should be built-in, but I tried pip installing cdifflib, ndifflib, pydiff with the same result.  Just for fun I also tried installing diff, which installs a few prerequisites, including attrs, which until it is removed gives me "invalid syntax" in _next_gen.py on the next compile; once that's removed I get the same as above.

**Error message**
```
  File "FoFiX.py", line 108, in <module>
  File "GameEngine.pyo", line 32, in <module>
  File "numpy\__init__.pyo", line 187, in <module>
  File "numpy\testing\__init__.pyo", line 10, in <module>
  File "unittest\__init__.pyo", line 59, in <module>
  File "unittest\case.pyo", line 6, in <module>
ImportError: No module named difflib
```
As a test, I commented out line 73 of setup_exe.py, "difflib", from options={"py2exe":...{"excludes":[]...}
This actually starts the game briefly, but then I get a runtime error in fofix.log:
```
[    0.000000] (D) Logging initialized: Fri Apr 22 15:22:51 2022
[    1.276000] (W) Pitch bending is not supported; install john.stumpo's pitchbend module (r7 or higher) if you want it.
[    1.792000] (D) GameEngine class init (GameEngine.py)...
[    1.792000] (D) FoFiX v3.123 Final starting up...
[    1.792000] (D) pygame version: 2.0.3
[    1.793000] (D) Initializing audio.
[    1.841000] (D) Audio configuration: (48000, -16, 8)
[    1.899000] (D) Initializing pygame.mixer & audio system at 44100 Hz.
[    1.899000] (D) Initializing video.
[    2.514000] (E) Terminating due to unhandled exception:
Traceback (most recent call last):
  File "FoFiX.py", line 276, in <module>
  File "FoFiX.py", line 175, in main
  File "GameEngine.pyo", line 550, in __init__
  File "Video.pyo", line 102, in setMode
  File "PIL\Image.pyo", line 2818, in open
IOError: cannot identify image file 'data\\fofix_icon.png'
```
"data\fofix_icon.png" does exist, and is a valid png file.  I tried replacing it with different png files: no change.  I tried commenting out lines 497-8 from GameEngine.py and 186 from Credits.py, but falling into "icon = None" results in a runtime "AttributeError: 'NoneType' object has no attribute 'read'"

**To Reproduce**
1. Fresh install of Python 2.7.18 (x86) on Windows 11 [Note I also tried ActivePython 2.7.18 (x86), but the result was similar, though note the state tool doesn't want to install anything; it seems perhaps because of the CVE in bzip 1.0.6.]
2. Note requirements.txt does not seem to exist anymore, so these were the prerequisites I figured my way through:
```
pip install pywin32 py2exe_py2 pyopengl pyopengl-accelerate pygame numpy pyaudio pillow python-gettext
```

**Environment (please complete the following information):**
 - OS: Windows 11
 - Python version: 2.7.18 (x86)

**Comment by Nutzzz** [comment]
Note that running "python FoFiX.py" in the src directory seems to work just fine.

**Comment by Nutzzz** [comment]
Using the latest master with the versions in requirements.txt, compiling with py2exe gives me an issue with distutils (another built-in):
```
Traceback (most recent call last):
  File "FoFiX.py", line 50, in <module>
    import PIL.JpegImagePlugin
  File "PIL\JpegImagePlugin.pyo", line 42, in <module>
  File "PIL\TiffImagePlugin.pyo", line 44, in <module>
ImportError: No module named distutils.version
```
Here, running "python FoFiX.py" gives me the pygame announce but then stops before a log is created.

**Comment by Linkid** [comment]
Hi! Thanks for your report. Is it possible to create a new issue for the 4.x version (the one in master), please?

**Comment by Linkid** [comment]
About `difflib`, it seems that numpy needs it. Which version of numpy are you using ?

**Comment by Nutzzz** [comment]
> Which version of numpy are you using ?
1.16.6
