### ISSUE TITLE
FoFiX crashes at the end of a song

### ISSUE THREAD

**Issue by Salamandar** [fofix/fofix#42]
Well, that one is an old bug. Maybe already fixed ? I'm using v4.0.0alpha2.r244.gd21b0cc-1

```
Traceback (most recent call last):
  File "./FoFiX.py", line 271, in <module>
    main.run()
  File "./FoFiX.py", line 253, in run
    while self.engine.run():
  File "/opt/fofix-git/fofix/core/GameEngine.py", line 599, in run
    rtn = self.mainloop()
  File "/opt/fofix-git/fofix/core/GameEngine.py", line 581, in main
    done = self.task.run()
  File "/opt/fofix-git/fofix/core/Task.py", line 104, in run
    self.runTask(taskData['task'], tick=self.engine.tickDelta)
  File "/opt/fofix-git/fofix/core/Task.py", line 91, in runTask
    task.run(tick)
  File "/opt/fofix-git/fofix/game/GameResultsScene.py", line 700, in run
    self.runScores()
  File "/opt/fofix-git/fofix/game/GameResultsScene.py", line 561, in runScores
    name = Dialogs.getText(self.engine, _("%d points is a new high score! Enter your name:") % self.finalScore[i], self.playerList[i].upname)
  File "/opt/fofix-git/fofix/game/Dialogs.py", line 1871, in getText
    _runDialog(engine, d)
  File "/opt/fofix-git/fofix/game/Dialogs.py", line 1860, in _runDialog
    engine.run()
  File "/opt/fofix-git/fofix/core/GameEngine.py", line 599, in run
    rtn = self.mainloop()
  File "/opt/fofix-git/fofix/core/GameEngine.py", line 581, in main
    done = self.task.run()
  File "/opt/fofix-git/fofix/core/Task.py", line 104, in run
    self.runTask(taskData['task'], tick=self.engine.tickDelta)
  File "/opt/fofix-git/fofix/core/Task.py", line 91, in runTask
    task.run(tick)
  File "/opt/fofix-git/fofix/game/GameResultsScene.py", line 717, in run
    self.song.info.save()
  File "/opt/fofix-git/fofix/game/Song.py", line 390, in save
    self._set("scores",        self.getObfuscatedScores(part))
  File "/opt/fofix-git/fofix/game/Song.py", line 369, in getObfuscatedScores
    return binascii.hexlify(cerealizer.dumps(s))
  File "/usr/lib/python2.7/site-packages/cerealizer/__init__.py", line 595, in dumps
    Dumper().dump(obj, s)
  File "/usr/lib/python2.7/site-packages/cerealizer/__init__.py", line 144, in dump
    self.collect(root_obj)
  File "/usr/lib/python2.7/site-packages/cerealizer/__init__.py", line 186, in collect
    handler.collect(obj, self)
  File "/usr/lib/python2.7/site-packages/cerealizer/__init__.py", line 357, in collect
    for i in obj.values(): dumper.collect(i)
  File "/usr/lib/python2.7/site-packages/cerealizer/__init__.py", line 186, in collect
    handler.collect(obj, self)
  File "/usr/lib/python2.7/site-packages/cerealizer/__init__.py", line 334, in collect
    for i in obj: dumper.collect(i)
  File "/usr/lib/python2.7/site-packages/cerealizer/__init__.py", line 186, in collect
    handler.collect(obj, self)
  File "/usr/lib/python2.7/site-packages/cerealizer/__init__.py", line 316, in collect
    for i in obj: dumper.collect(i)
  File "/usr/lib/python2.7/site-packages/cerealizer/__init__.py", line 185, in collect
    if not handler: raise NonCerealizableObjectError("Object of class/type '%s' cannot be cerealized! Use cerealizer.register to extend Cerealizer support to other classes." % obj.__class__)
cerealizer.NonCerealizableObjectError: Object of class/type '<type 'unicode'>' cannot be cerealized! Use cerealizer.register to extend Cerealizer support to other classes.
```

**Comment by mdsitton** [comment]
i world recommend running from git, alpa 2 is 3 years old now... If you need any clarifications on getting it working i'm happy to provide them.

**Comment by Salamandar** [comment]
Sorry to have disappeared, I had some BIG deadline last night :D
Well I compiled fofix from git only some weeks ago, then this bug appeared.
I'll try to get the new version with the shared code working.

**Comment by mdsitton** [comment]
Just btw this looks like a bug with cerealizer and unicode objects when saving scores. As i mentioned somewhere i really want to stop saving scores in the ini files, and maybe remove the current implementation of score upload(it uses cerealizer as well).

**Comment by Linkid** [comment]
Yes, this bug comes from the `cerealizer` lib. You need to install it *the right way* for now (see https://bitbucket.org/jibalamy/cerealizer).
