### ISSUE TITLE
fofix is looking for missing ./data/songs/notes.mid

### ISSUE THREAD

**Issue by fculpo** [fofix/fofix#53]
Ubuntu 14.04 desktop

When launching practice, seems the game is looking for ./data/songs/notes.mid
data/songs does not exist 

Traceback (most recent call last):
  File "FoFiX.py", line 288, in <module>
    main.run()
  File "FoFiX.py", line 270, in run
    while self.engine.run():
  File "/fofix/fofix/core/GameEngine.py", line 601, in run
    rtn = self.mainloop()
  File "/fofix/fofix/core/GameEngine.py", line 583, in main
    done = self.task.run()
  File "/usr/local/lib/python2.7/dist-packages/fretwork/task.py", line 111, in run
    self.runTask(taskData['task'])
  File "/usr/local/lib/python2.7/dist-packages/fretwork/task.py", line 91, in runTask
    task.run(tick)
  File "/fofix/fofix/core/Input.py", line 319, in run
    self.broadcastEvent(self.keyListeners, "keyPressed", event.key, event.unicode)
  File "/fofix/fofix/core/Input.py", line 230, in broadcastEvent
    if getattr(l, function)(*args):
  File "/fofix/fofix/game/SongChoosingScene.py", line 851, in keyPressed
    self.startGame()
  File "/fofix/fofix/game/SongChoosingScene.py", line 528, in startGame
    info = Song.loadSongInfo(self.engine, self.songName, library = self.libraryName)
  File "/fofix/fofix/game/Song.py", line 3294, in loadSongInfo
    return SongInfo(infoFile, library)
  File "/fofix/fofix/game/Song.py", line 262, in __init__
    songhash = hashlib.sha1(open(self.noteFileName, 'rb').read()).hexdigest()
IOError: [Errno 2] No such file or directory: u'/fofix/data/songs/notes.mid'

**Comment by mdsitton** [comment]
I haven't ran into this bug, i know practice mode has its problems currently, but i haven't seen this one.

**Comment by shikulja** [comment]
on windows
`Traceback (most recent call last):
  File "FoFiX.py", line 312, in <module>
  File "FoFiX.py", line 294, in run
  File "fofix\core\GameEngine.pyo", line 600, in run
  File "fofix\core\GameEngine.pyo", line 582, in main
  File "fretwork\task.pyo", line 114, in run
  File "fretwork\task.pyo", line 89, in runTask
  File "fofix\core\Input.pyo", line 319, in run
  File "fofix\core\Input.pyo", line 230, in broadcastEvent
  File "fofix\game\Lobby.pyo", line 345, in keyPressed
  File "fofix\game\World.pyo", line 86, in startGame
  File "fofix\game\World.pyo", line 124, in createScene
  File "fofix\core\SceneFactory.pyo", line 36, in create
  File "fofix\game\SongChoosingScene.pyo", line 67, in __init__
  File "fofix\game\song\song.pyo", line 3397, in updateSongDatabase
  File "fofix\game\song\song.pyo", line 3010, in getAvailableSongs
  File "fofix\game\song\song.pyo", line 268, in __init__
IOError: [Errno 2] No such file or directory: 'C:\\Users\\User\\AppData\\Roaming\\fofix\\songs\\Guitar Hero Metallica\\1.01-For Whom The Bell Tolls\\notes.mid'`

**Comment by shikulja** [comment]
only help adding, 
[game]
base_library = [path]
i fink it is need fix

Traceback (most recent call last):
  File "FoFiX.py", line 312, in <module>
  File "FoFiX.py", line 294, in run
  File "fofix\core\GameEngine.pyo", line 600, in run
  File "fofix\core\GameEngine.pyo", line 582, in main
  File "fretwork\task.pyo", line 114, in run
  File "fretwork\task.pyo", line 89, in runTask
  File "fofix\core\Input.pyo", line 319, in run
  File "fofix\core\Input.pyo", line 230, in broadcastEvent
  File "fofix\game\SongChoosingScene.pyo", line 843, in keyPressed
  File "fofix\game\SongChoosingScene.pyo", line 631, in startGame
  File "fofix\game\World.pyo", line 124, in createScene
  File "fofix\core\SceneFactory.pyo", line 36, in create
  File "fofix\game\guitarscene\GuitarScene.pyo", line 1209, in __init__
  File "fofix\core\Resource.pyo", line 239, in load
  File "fofix\core\Resource.pyo", line 114, in load
  File "fofix\game\guitarscene\GuitarScene.pyo", line 1209, in <lambda>
  File "fofix\game\song\song.pyo", line 2841, in loadSong
WindowsError: [Error 3] : 'songs\\Guitar Hero Metallica\\Metallica - ...And Justice for All\\'
