### ISSUE TITLE
Bug in cerealizer ?

### ISSUE THREAD

**Issue by Salamandar** [fofix/fofix#63]
Fresh linux/python/fofix install.

```
Traceback (most recent call last):
  File "./FoFiX.py", line 156, in <module>
    from fofix.core.VideoPlayer import VideoLayer, VideoPlayerError
  File "/opt/fofix-git/fofix/core/VideoPlayer/__init__.py", line 1, in <module>
    from fofix.lib._VideoPlayer import *
  File "fofix/core/VideoPlayer/_VideoPlayer.pyx", line 100, in init fofix.core.VideoPlayer._VideoPlayer (fofix/core/VideoPlayer/_VideoPlayer.c:4286)
    from fofix.core.Input import KeyListener
  File "/opt/fofix-git/fofix/core/Input.py", line 39, in <module>
    from fofix.core.Player import Controls
  File "/opt/fofix-git/fofix/core/Player.py", line 34, in <module>
    from fofix.game import song
  File "/opt/fofix-git/fofix/game/song/__init__.py", line 1, in <module>
    from fofix.game.song.song import *
  File "/opt/fofix-git/fofix/game/song/song.py", line 36, in <module>
    import cerealizer
  File "/usr/lib/python2.7/site-packages/cerealizer/__init__.py", line 562, in <module>
    register(str       , StrHandler      ())
  File "/usr/lib/python2.7/site-packages/cerealizer/__init__.py", line 515, in register
    if Class in _HANDLERS_: raise ValueError("Class %s has already been registred!" % Class)
ValueError: Class <type 'str'> has already been registred!
```

What is the problem here ?

**Comment by Salamandar** [comment]
BTW it seems to me I already had a similar error, a long time ago.

**Comment by Salamandar** [comment]
I commented the line 562, now it works. But what's the problem ?

**Comment by mdsitton** [comment]
What version of cerealizer are you using?

**Comment by Salamandar** [comment]
I'm using the 0.8.1 though :

    pkgver=0.8.1
    source=(https://pypi.python.org/packages/source/C/Cerealizer/Cerealizer-${pkgver}.tar.bz2)

**Comment by mdsitton** [comment]
I'm really not sure whats going on here. At some point i plan to get rid of the need to use cerealizer anyways. all its really used for atm is to upload scores to some kind of score tracking service (all of which are currently dead i think), and to save scores in ini files. So scores in the ini files imo are a bad idea, so eventually they will probably end up in an sqlite database somewhere.

**Comment by SajeOne** [comment]
I get this as well. Pulling the git repo with the fofix-git AUR package on arch.

```
Traceback (most recent call last):
  File "./FoFiX.py", line 156, in <module>
    from fofix.core.VideoPlayer import VideoLayer, VideoPlayerError
  File "/opt/fofix-git/fofix/core/VideoPlayer/__init__.py", line 1, in <module>
    from fofix.lib._VideoPlayer import *
  File "fofix/core/VideoPlayer/_VideoPlayer.pyx", line 100, in init fofix.core.VideoPlayer._VideoPlayer (fofix/core/VideoPlayer/_VideoPlayer.c:4286)
    from fofix.core.Input import KeyListener
  File "/opt/fofix-git/fofix/core/Input.py", line 39, in <module>
    from fofix.core.Player import Controls
  File "/opt/fofix-git/fofix/core/Player.py", line 34, in <module>
    from fofix.game import song
  File "/opt/fofix-git/fofix/game/song/__init__.py", line 1, in <module>
    from fofix.game.song.song import *
  File "/opt/fofix-git/fofix/game/song/song.py", line 36, in <module>
    import cerealizer
  File "/usr/lib/python2.7/site-packages/cerealizer/__init__.py", line 562, in <module>
    register(str       , StrHandler      ())
  File "/usr/lib/python2.7/site-packages/cerealizer/__init__.py", line 515, in register
    if Class in _HANDLERS_: raise ValueError("Class %s has already been registred!" % Class)
ValueError: Class <type 'str'> has already been registred!
```


Using AUR package python2-cerealizer(Version 0.8.1-2)

**Comment by mdsitton** [comment]
Ok so installing the version of cerealizer with pip works fine, the AUR package doesnt work fine... So technically this is an issue with the AUR package...
