### ISSUE TITLE
File Path Error

### ISSUE THREAD

**Issue by TapdancingRodent** [fofix/fofix#64]
I got the following when I tried to load any song on my system (Linux Mint). Fixed seemingly without side effects (although it isnt a universal fix!) by changing line 2840 of fofix/songs/songs.py to:
os.chdir("{1}{0}{2}{0}".format(os.path.sep, "data/" + library, name))

FoFiX had successfully cached all of the songs I'd put into data/songs but wasn't looking on the right path to open them.

/home/sardines/.fofix/fofix.log
The log file already includes the traceback given above.
Traceback (most recent call last):
  File "FoFiX.py", line 312, in <module>
    main.run()
  File "FoFiX.py", line 294, in run
    while self.engine.run():
  File "/home/sardines/local/fofix-master/fofix/core/GameEngine.py", line 600, in run
    rtn = self.mainloop()
  File "/home/sardines/local/fofix-master/fofix/core/GameEngine.py", line 582, in main
    done = self.task.run()
  File "/usr/local/lib/python2.7/dist-packages/fretwork/task.py", line 114, in run
    self.runTask(taskData['task'])
  File "/usr/local/lib/python2.7/dist-packages/fretwork/task.py", line 89, in runTask
    task.run(tick)
  File "/home/sardines/local/fofix-master/fofix/core/Input.py", line 319, in run
    self.broadcastEvent(self.keyListeners, "keyPressed", event.key, event.unicode)
  File "/home/sardines/local/fofix-master/fofix/core/Input.py", line 230, in broadcastEvent
    if getattr(l, function)(_args):
  File "/home/sardines/local/fofix-master/fofix/game/SongChoosingScene.py", line 843, in keyPressed
    self.startGame()
  File "/home/sardines/local/fofix-master/fofix/game/SongChoosingScene.py", line 631, in startGame
    self.engine.world.createScene("GuitarScene", libraryName = self.libraryName, songName = self.songName)
  File "/home/sardines/local/fofix-master/fofix/game/World.py", line 124, in createScene
    self.scene = SceneFactory.create(engine = self.engine, name = name, *_args)
  File "/home/sardines/local/fofix-master/fofix/core/SceneFactory.py", line 36, in create
    return getattr(scene_name, name)(engine = engine, **args)
  File "/home/sardines/local/fofix-master/fofix/game/guitarscene/GuitarScene.py", line 1209, in **init**
    self.engine.resource.load(self, "song", lambda: loadSong(self.engine, songName, library = libraryName, part = [player.part for player in self.players], practiceMode = self.players[0].practiceMode, practiceSpeed = self.players[0].practiceSpeed), synch = True, onLoad = self.songLoaded)
  File "/home/sardines/local/fofix-master/fofix/core/Resource.py", line 239, in load
    return l.finish()
  File "/home/sardines/local/fofix-master/fofix/core/Resource.py", line 114, in load
    self.result = self.function()
  File "/home/sardines/local/fofix-master/fofix/game/guitarscene/GuitarScene.py", line 1209, in <lambda>
    self.engine.resource.load(self, "song", lambda: loadSong(self.engine, songName, library = libraryName, part = [player.part for player in self.players], practiceMode = self.players[0].practiceMode, practiceSpeed = self.players[0].practiceSpeed), synch = True, onLoad = self.songLoaded)
  File "/home/sardines/local/fofix-master/fofix/game/song/song.py", line 2840, in loadSong
    os.chdir("{1}{0}{2}{0}".format(os.path.sep, library, name))
OSError: [Errno 2] No such file or directory: 'songs/Guitar Hero III Legends Of Rock/DLC/DLC 15 - Muse Track Pack/Muse - Supermassive Black Hole/'

**Comment by mdsitton** [comment]
Try re-selecting your song library location in "options > setlist settings > Change Setlist Path"
