### ISSUE TITLE
[OSX] running from sources fails

### ISSUE THREAD

**Issue by RomainQuidet** [fofix/fofix#65]
Hi,
I installed all required dependencies, build and install fretwork, then tried to run fofix. 
It fails with this
`➜  fofix git:(master) python FoFiX.py 
Traceback (most recent call last):
  File "FoFiX.py", line 156, in <module>
    from fofix.core.VideoPlayer import VideoLayer, VideoPlayerError
  File "/Users/romain/Documents/dev/fofix/fofix/core/VideoPlayer/__init__.py", line 1, in <module>
    from fofix.lib._VideoPlayer import *
ImportError: No module named _VideoPlayer
`

**Comment by mdsitton** [comment]
I guess you figured this out?

**Comment by RomainQuidet** [comment]
Yes sorry to bother you, I missed the native video build part. I managed to make it.
Now I just got cerealizer failing on my OS X configuration … have you ever seen that ?

fofix git:(master) python FoFiX.py                            
Traceback (most recent call last):
  File "FoFiX.py", line 156, in <module>
    from fofix.core.VideoPlayer import VideoLayer, VideoPlayerError
  File "/Users/romain/Documents/dev/fofix/fofix/core/VideoPlayer/__init__.py", line 1, in <module>
    from fofix.lib._VideoPlayer import *
  File "fofix/core/VideoPlayer/_VideoPlayer.pyx", line 100, in init fofix.core.VideoPlayer._VideoPlayer (fofix/core/VideoPlayer/_VideoPlayer.c:4298)
    from fofix.core.Input import KeyListener
  File "/Users/romain/Documents/dev/fofix/fofix/core/Input.py", line 39, in <module>
    from fofix.core.Player import Controls
  File "/Users/romain/Documents/dev/fofix/fofix/core/Player.py", line 34, in <module>
    from fofix.game import song
  File "/Users/romain/Documents/dev/fofix/fofix/game/song/__init__.py", line 1, in <module>
    from fofix.game.song.song import *
  File "/Users/romain/Documents/dev/fofix/fofix/game/song/song.py", line 36, in <module>
    import cerealizer
  File "/usr/local/lib/python2.7/site-packages/cerealizer/__init__.py", line 11, in <module>
    execfile("%s.py2" % __file__.rsplit(".", 1)[0])
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/cerealizer/__init__.py2’

Thanks,

Romain

**Comment by RomainQuidet** [comment]
I'm using pip and python2.7
'pip list
Cerealizer (0.8.1)'

**Comment by RomainQuidet** [comment]
seems that cerealizer install was corrupted, needed to install manually. No crash anymore
